### ISSUE TITLE
Question: Restrict access to the frontend

### ISSUE THREAD

**Issue by thpreisler** [brennerm/docker-registry-frontend#15]
Hi, very useful tool! I was just wondering if it is possible to restrict access to the frontend itself, with basic or something else?
Best Thomas

**Comment by mikaellindemann** [comment]
If you run this in docker, it is easily achieved by putting e.g. traefik in front of the registry frontend.

This means that traefik will listen to the desired port, check that the authentication header matches a user/password combination, and forward the request to the registry frontend only if a match is found.

Using a reverse proxy such as traefik will also allow you to run multiple web services on the same machine, using different rules for routing requests.

This will be the flow of a request:
Browser -> HTTP(S) -> traefik -> HTTP -> docker-registry-frontend

**Comment by brennerm** [comment]
I can agree with @mikaellindemann. Right now I have no plan to integrate any kind of user management and authentication into this project. If you need some level of restriction you can achieve this by using a web server (nginx, Apache, traefik, ...) as a Basic Auth proxy. Feel free to contact me for detailed instructions.

**Comment by thpreisler** [comment]
Thanks! I ended up using a nginx docker container as a reverse proxy for SSL encryption and basic auth.
