### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by gtorre** [brennerm/docker-registry-frontend#3]
@brennerm I tried running the image from docker hub, and it fails to start:

```
[root~]# docker run -p 127.0.0.1:80:80 brennerm/docker-registry-frontend
 * Starting nginx nginx
   ...done.
Fatal Python error: getrandom() failed
Aborted (core dumped)
```
Kernel: `3.10.0-229.el7.x86_64`

**Comment by brennerm** [comment]
Unfortunately I'm not able to reproduce this issue on my side. I installed a VM running CentOS with the same kernel version that you use and can start a Docker container without any problem.

Do you still have an issue with getting the Docker image to work?

**Comment by brennerm** [comment]
Closing due to no response.
